# Generated by Django 2.2.13 on 2022-05-15 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=320)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('town_name', models.CharField(max_length=30)),
                ('star_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_manager', to='resort_app.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('summer_temp', models.FloatField()),
                ('winter_temp', models.FloatField()),
                ('sealevel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_guest', to='resort_app.Guest')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_resort', to='resort_app.Resort')),
            ],
        ),
        migrations.AddField(
            model_name='resort',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_town', to='resort_app.Town'),
        ),
        migrations.CreateModel(
            name='PointofInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describes', models.CharField(max_length=30)),
                ('open_time', models.CharField(max_length=30)),
                ('close_time', models.CharField(max_length=30)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_town', to='resort_app.Town')),
            ],
        ),
        migrations.CreateModel(
            name='CabinCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('rate', models.PositiveIntegerField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_cost_resort', to='resort_app.Resort')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describes', models.CharField(max_length=30)),
                ('cabin_type', models.CharField(max_length=10)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('sleep_capacity', models.PositiveIntegerField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_resort', to='resort_app.Resort')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('adult_count', models.PositiveIntegerField()),
                ('child_count', models.PositiveIntegerField()),
                ('pet_count', models.PositiveIntegerField()),
                ('total_charge', models.PositiveIntegerField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_cabin', to='resort_app.Cabin')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_guest', to='resort_app.Guest')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_resort', to='resort_app.Resort')),
            ],
        ),
    ]
