# Generated by Django 2.2.13 on 2022-05-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort_app', '0002_auto_20220516_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='town_name',
        ),
    ]
