# Generated by Django 2.2.13 on 2022-05-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort_app', '0003_remove_resort_town_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
