# Generated by Django 2.2.13 on 2022-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_app', '0004_auto_20220523_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
