# Generated by Django 2.2.13 on 2022-05-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort_app', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
